### ISSUE TITLE
0x800700b7 Config section 'system.webServer/security/requestFiltering' already defined.

### ISSUE THREAD

**Issue by mdroegegit** [michelderooij/Configure-ClientSizeLimits#1]
We are using the script on Exchange 2016CU11. In the FrontEnd OWA web.config it created an additional system.webServer and system.web node at the bottom of the file instead of using the existing one.  When opening OWA/ECP this results in the error:

Error Code
   0x800700b7 

Config Error
   Config section 'system.webServer/security/requestFiltering' already defined. Sections must only appear once per config file. See the help topic <location> for exceptions  

Config File
   \\?\D:\ExchangeServer\FrontEnd\HttpProxy\owa\web.config 

Anything we can do to prevent this from happening?

**Comment by michelderooij** [comment]
Creating accidental duplicated should be fixed by now. Please reopen when it happens again.
